import os
import json
from dotenv import load_dotenv
from sqlmodel import SQLModel
from google import genai
from google.genai import types
from models.models import Listing, Venue

def generate():
    
    load_dotenv(override=True)

    client = genai.Client(
        api_key=os.environ.get("GEMINI_API_KEY"),
    )

    model = "gemini-2.5-flash-lite" 
    
    prompt_text = (
        "Thoroughly research the 'Craigmillar Park Tennis & Padel Club' in Edinburgh. "
        "Your task is to extract ALL available operational, contact, and facility data. "
        "Populate every field in the provided JSON schema using the grounding tools."
    )
    
    contents = [
        types.Content(
            role="user",
            parts=[
                types.Part.from_text(text=prompt_text),
            ],
        ),
    ]

    # --- CONFIGURE THE REQUEST ---
    generate_content_config = types.GenerateContentConfig(
        response_mime_type="application/json",
        response_schema=Listing,
        temperature=0.1, 
        tools=[
            types.Tool(google_search=types.GoogleSearch()),
            types.Tool(google_maps=types.GoogleMaps()),
        ],
    )

    print(f"--- Running {model} for RAW JSON Output ---")
    
    try:        
        response = client.models.generate_content(
            model=model,
            contents=contents,
            config=generate_content_config,
        )
                
        print("\n" + "="*50)
        print("RAW MODEL RESPONSE (Full JSON Schema Output):")
        print("="*50)
        
        # Use json.dumps to pretty-print the JSON string for better readability
        # The response.text is the JSON string generated by the model
        parsed_json = json.loads(response.text)
        print(json.dumps(parsed_json, indent=4)) 
        
    except Exception as e:
        print(f"\n\nAn API Error occurred. Full error: {e}")

    print("\n--- End of Execution ---")

if __name__ == "__main__":
    generate()